spring:
  datasource:
    url: jdbc:h2:file:~\stickersdb
    #url: jdbc:h2:file:.\src\main\resources\stickers_db\stickersdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

# actuator
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include:*
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
